function suggestTask() {
    var name = document.getElementById("name").value;
    var age = document.getElementById("age").value;

    if (name && age) {
        var tasks = [
            "Watch a movie",
            "Read a book",
            "Go for a walk",
            "Write in a journal",
            "Listen to music",
            "Try a new recipe",
            "Learn a new language",
            "Do a puzzle",
            "Meditate for 10 minutes",
            "Take a nap",
            "Visit a museum",
            "Go to the gym",
            "Start a blog",
            "Paint or draw",
            "Attend a fitness class",
            "Volunteer at a local charity",
            "Take a photography walk",
            "Visit a friend",
            "Learn to play a musical instrument",
            "Do a DIY project",
            "Plan a weekend getaway",
            "Try a new restaurant",
            "Take a dance class",
            "Practice yoga",
            "Explore a nearby park",
            "Write a letter to a friend or family member",
            "Go to a live performance (concert, play, etc.)",
            "Take a day trip to a nearby town",
            "Organize your closet",
            "Start a book club",
            "Visit a farmers market",
            "Have a picnic",
            "Take a digital detox for a day",
            "Visit a local library",
            "Do a random act of kindness",
            "Attend a workshop or seminar",
            "Visit a botanical garden",
            "Create a vision board",
            "Play a board game",
            "Try a new sport",
            "Explore a new hobby",
            "Take a scenic drive",
            "Have a spa day at home",
            "Write a short story",
            "Learn to code",
            "Take a cooking class",
            "Join a meetup group",
            "Go stargazing",
            "Visit an art gallery",
            "Start a fitness challenge",
            "Plant a garden",
            "Host a potluck dinner",
            "Try a new workout routine",
            "Attend a comedy show",
            "Take a historical tour",
            "Learn to juggle",
            "Visit a beach or lake",
            "Go camping",
            "Take a bike ride",
            "Explore a new trail",
            "Learn origami",
            "Have a karaoke night",
            "Attend a local festival",
            "Take a day off and relax",
            "Write poetry",
            "Create a scrapbook",
            "Take a class online",
            "Visit an escape room",
            "Try a virtual reality experience",
            "Build a sandcastle",
            "Take a scenic train ride",
            "Visit a planetarium",
            "Try geocaching",
            "Take a hot air balloon ride",
            "Learn to meditate",
            "Have a movie marathon",
            "Take a scenic boat ride",
            "Try indoor rock climbing",
            "Take a pottery class",
            "Learn calligraphy",
            "Visit a historical landmark",
            "Go horseback riding",
            "Try a new ice cream flavor",
            "Take a painting class",
            "Join a community garden",
            "Visit an aquarium",
            "Go zip-lining",
            "Learn to knit or crochet",
            "Take a cooking class",
            "Go rollerblading",
            "Try a virtual museum tour",
            "Attend a poetry reading",
            "Take a helicopter tour",
            "Learn to make cocktails",
            "Visit a science museum"
        ];

        // Get a random task
        var randomTask = tasks[Math.floor(Math.random() * tasks.length)];
        console.log("Random Task: " + randomTask);

        // Display the task suggestion
        document.getElementById("taskSuggestion").innerHTML = "Task for " + name + " (" + age + " years old): " + randomTask;

    } else {
        // Display an error message if name or age is missing
        document.getElementById("taskSuggestion").innerHTML = "Please enter both your name and age.";
    }
}
